### ISSUE TITLE
Regression with VS 2019 Update 16.2+

### ISSUE THREAD

**Issue by smkanadl** [xkbeyer/CatchTestAdapter#21]
After updating Visual Studio to the 16.2 release with the improved test explorer, the test adapter stopped working correctly.

 * Sometimes tests are not discovered. It needs a recompilation to let them be found.
 * Running tests is not possible any more. Tests are simply not run without any output in the Test pane.

It worked fine in VS2019 16.0 and 16.1.

**Comment by xkbeyer** [comment]
Unfortunately, the new TestExplorer does not work as before. It is no longer possible to add new TestCases after the run of Discover. At the moment I haven't found a way to do this again. Since Catch does not list the SECTIONS (--list-tests), the adapter added them after a run and so the hirarchy could be displayed accordingly. 
At the moment I only see the possibility to display the SECTION results in the Test Detail Summary window. This means, no hierarchical display of the TEST_CASE and SECTION anymore, which would be a pity.
So that the adapter works again, I have to rewrite it accordingly and do without the hierarchical view.

**Comment by smkanadl** [comment]
That's what I suspected. But rolling back the section stuff will at least work, which is better than nothing at all. Probably its time to bring the section issue to the offical catch repo?

**Comment by xkbeyer** [comment]
I agree, first I'm gonna get it working again.

**Comment by xkbeyer** [comment]
I reworked the test executer so that it runs with version 16.2 and newer. Sections are now reported es sub results and shown in the result pane of the test explorer.
@smkanadl If you like please test the attached version.
[CatchTestAdapter.VsPackage.zip](https://github.com/xkbeyer/CatchTestAdapter/files/4140879/CatchTestAdapter.VsPackage.zip)
Please clean your test project. VS caches somehow the information which test runner was run and doesn't run the old exe with the new test adapter.

**Comment by smkanadl** [comment]
Hi,

I gave it a try on one of out projects and it worked pretty well. Many thanks for your effort!

**Comment by xkbeyer** [comment]
Release Version 1.6.0 includes the fix.
